# Generated by Django 5.0.7 on 2024-07-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Ilustración 1'),
        ),
        migrations.AddField(
            model_name='producto',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Ilustración 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Ilustración 3'),
        ),
        migrations.AddField(
            model_name='producto',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Ilustración 4'),
        ),
    ]
