# Generated by Django 5.0.7 on 2024-08-05 00:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default='2024-01-01'),  # Default value changed to a valid date
            preserve_default=False,
        ),
    ]
