# Generated by Django 5.0.7 on 2024-08-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_turno_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
    ]
