# Generated by Django 5.0.7 on 2024-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
