# Generated by Django 4.0.6 on 2025-01-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Artículo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Imagen 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Imagen 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Imagen 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Imagen 5')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Imagen 6')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='miapp.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
