# Generated by Django 4.0.6 on 2025-08-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0015_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='detalle_productos',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle de productos'),
        ),
    ]
